version: "3"
services:
  php:
    build: docker/php
    volumes:
      - .:/app:cached

      # for xdebug
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      # end for xdebug
    working_dir: /app

    # this container name has to be set also in default.conf
    container_name: symfony_mysql_example_php
    depends_on:
      - mysql

  nginx:
    image: nginx:1.15.0
    ports:
      - 127.0.0.1:${NGINX_PORT}:80
    volumes:
      - .:/app:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
    container_name: symfony_mysql_example_nginx
    depends_on:
      - php

  mysql:
    image: mysql:5.7
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    ports:
      - 127.0.0.1:${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DB_NAME: ${MYSQL_DB_NAME}
    container_name: symfony_mysql_example_mysql
